# Config unique to Flanders

monitor=desc:Ancor Communications Inc ASUS VS229 JCLMTF198590,1920x1080,0x0,1
monitor=desc:Ancor Communications Inc ASUS VS228 D9LMTF093107,1920x1080,1920x0,1
monitor=eDP-1,2560x1600,1280x1080,1

workspace = 1, monitor:desc:Ancor Communications Inc ASUS VS229 JCLMTF198590
workspace = 2, monitor:desc:Ancor Communications Inc ASUS VS229 JCLMTF198590
workspace = 3, monitor:desc:Ancor Communications Inc ASUS VS228 D9LMTF093107
workspace = 4, monitor:desc:Ancor Communications Inc ASUS VS228 D9LMTF093107
workspace = 5, monitor:DP-1

 # Launch apps
exec-once = [workspace 1 silent] mattermost-desktop
exec-once = [workspace 2 silent] firefox
exec-once = [workspace 4 silent] kitty

# Bluetooth systray
exec-once = blueman-applet
exec-once = nm-applet
