# Config unique to Nelson
monitor=eDP-1,1920x1200,1920x1080,1

 # Launch apps
exec-once = [workspace 1 silent] slack
exec-once = [workspace 2 silent] firefox
exec-once = [workspace 4 silent] kitty

# Bluetooth systray
exec-once = blueman-applet
exec-once = nm-applet
