require("core.plugin_config.bufferline")
require("core.plugin_config.completions")
require("core.plugin_config.lsp_config")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-autopairs")
require("core.plugin_config.nvim-neoclip")
require("core.plugin_config.nvim-surround")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")

-- themes
-- require("core.plugin_config.gruvbox")
-- require("core.plugin_config.rose-pine")
require("core.plugin_config.codedark")
