require("core.plugin_config.catppuccin")
require("core.plugin_config.indent_blankline")
require("core.plugin_config.gitsigns")
require("core.plugin_config.lsp_config")
require("core.plugin_config.lualine")
require("core.plugin_config.mkdnflow-nvim")
require("core.plugin_config.navigator-nvim")
require("core.plugin_config.nvim-autopairs")
require("core.plugin_config.nvim-neoclip")
require("core.plugin_config.nvim-neo-tree")
require("core.plugin_config.nvim-surround")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")

-- themes
-- require("core.plugin_config.gruvbox")
-- require("core.plugin_config.rose-pine")
require("core.plugin_config.codedark")
